// <auto-generated />
using System;
using AccessFlow.Directory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessFlow.Directory.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    [Migration("20260930205341_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("directory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessFlow.Directory.AccessSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProvisioningUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("systems", "directory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000101"),
                            Name = "Jira",
                            OwnerId = new Guid("0198f3a0-0000-7000-8000-000000000001"),
                            ProvisioningUrl = "http://localhost:5199/provisioning/jira"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000102"),
                            Name = "GitLab",
                            OwnerId = new Guid("0198f3a0-0000-7000-8000-000000000002"),
                            ProvisioningUrl = "http://localhost:5199/provisioning/gitlab"
                        });
                });

            modelBuilder.Entity("AccessFlow.Directory.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("users", "directory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000001"),
                            Name = "Alice"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000002"),
                            Name = "Bob"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000003"),
                            Name = "Carol"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000004"),
                            Name = "Dave"
                        });
                });

            modelBuilder.Entity("AccessFlow.Directory.AccessSystem", b =>
                {
                    b.HasOne("AccessFlow.Directory.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
