// <auto-generated />
using System;
using AccessFlow.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessFlow.Api.Persistence.Migrations
{
    [DbContext(typeof(AccessFlowDbContext))]
    [Migration("20261005201253_AccessRequestDecision")]
    partial class AccessRequestDecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessFlow.AccessRequests.AccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("SystemId");

                    b.HasIndex("BeneficiaryId", "SystemId")
                        .IsUnique()
                        .HasDatabaseName("IX_access_requests_active_BeneficiaryId_SystemId")
                        .HasFilter("\"Status\" IN ('Pending', 'Approved')");

                    b.ToTable("access_requests", "access_requests");
                });

            modelBuilder.Entity("AccessFlow.AccessRequests.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<string>("StatusAfter")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StatusBefore")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccessRequestId");

                    b.HasIndex("ActorId");

                    b.ToTable("audit_log", "access_requests");
                });

            modelBuilder.Entity("AccessFlow.Directory.AccessSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProvisioningUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("systems", "directory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000101"),
                            Name = "Jira",
                            OwnerId = new Guid("0198f3a0-0000-7000-8000-000000000001"),
                            ProvisioningUrl = "http://localhost:5199/provisioning/jira"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000102"),
                            Name = "GitLab",
                            OwnerId = new Guid("0198f3a0-0000-7000-8000-000000000002"),
                            ProvisioningUrl = "http://localhost:5199/provisioning/gitlab"
                        });
                });

            modelBuilder.Entity("AccessFlow.Directory.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("users", "directory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000001"),
                            Name = "Alice"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000002"),
                            Name = "Bob"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000003"),
                            Name = "Carol"
                        },
                        new
                        {
                            Id = new Guid("0198f3a0-0000-7000-8000-000000000004"),
                            Name = "Dave"
                        });
                });

            modelBuilder.Entity("AccessFlow.AccessRequests.AccessRequest", b =>
                {
                    b.HasOne("AccessFlow.Directory.User", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessFlow.Directory.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessFlow.Directory.AccessSystem", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessFlow.AccessRequests.AuditLogEntry", b =>
                {
                    b.HasOne("AccessFlow.AccessRequests.AccessRequest", null)
                        .WithMany()
                        .HasForeignKey("AccessRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessFlow.Directory.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AccessFlow.Directory.AccessSystem", b =>
                {
                    b.HasOne("AccessFlow.Directory.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
